// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaR54nGAnOrQyzB6RnagUfF9Evy-28Vvk',
    appId: '1:496359542477:web:0c355f52ec4c43697d2384',
    messagingSenderId: '496359542477',
    projectId: 'flutter-project-927b4',
    authDomain: 'flutter-project-927b4.firebaseapp.com',
    storageBucket: 'flutter-project-927b4.firebasestorage.app',
    measurementId: 'G-ZMZTX5RJYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQF_fs1aXkOBf3wBgoGOvxogJiylB9wlQ',
    appId: '1:496359542477:android:a1a9218fff7024a47d2384',
    messagingSenderId: '496359542477',
    projectId: 'flutter-project-927b4',
    storageBucket: 'flutter-project-927b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCGj-EaLYFsLtZE2MgqXl5Jx37i_0A0Pw',
    appId: '1:496359542477:ios:eac210a28edc6a727d2384',
    messagingSenderId: '496359542477',
    projectId: 'flutter-project-927b4',
    storageBucket: 'flutter-project-927b4.firebasestorage.app',
    iosClientId: '496359542477-citlanh897okkmfu6rc85dok52c1kpfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.voqula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCGj-EaLYFsLtZE2MgqXl5Jx37i_0A0Pw',
    appId: '1:496359542477:ios:eac210a28edc6a727d2384',
    messagingSenderId: '496359542477',
    projectId: 'flutter-project-927b4',
    storageBucket: 'flutter-project-927b4.firebasestorage.app',
    iosClientId: '496359542477-citlanh897okkmfu6rc85dok52c1kpfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.voqula',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaR54nGAnOrQyzB6RnagUfF9Evy-28Vvk',
    appId: '1:496359542477:web:c7ae59e5d85907dc7d2384',
    messagingSenderId: '496359542477',
    projectId: 'flutter-project-927b4',
    authDomain: 'flutter-project-927b4.firebaseapp.com',
    storageBucket: 'flutter-project-927b4.firebasestorage.app',
    measurementId: 'G-76LYKZ6H79',
  );
}
